name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        minor-version: [6, 7, 8]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-versions: 3.${{ matrix.minor-version }}

      - name: Install gfortran for building OpenBLAS
        run: |
          sudo apt update
          sudo apt install -y gfortran

      - name: Install maturin
        run: |
          pip3 install maturin
          pip3 show maturin
          echo "::add-path::$HOME/.local/bin"

      - name: Build wheel
        run: maturin build --manylinux=off

      - name: Test
        run: |
          python -m pip install $(find target/wheels -name "*cp3${{ matrix.minor-version }}*.whl")
          python -c "import pyo3_linalg_example"
