name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  package:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2

    - name: install gfortran
      run: sudo apt update && sudo apt install -y gfortran

    - uses: actions/setup-python@v2
      with:
        python-versions: ${{ matrix.python-version }}

    - name: install maturin
      run: |
        pip3 install maturin
        pip3 show maturin
        echo "::add-path::$HOME/.local/bin"

    - name: Build wheel
      run: maturin build --manylinux=off

    - name: Test wheel
      run: |
        python -m pip install $(find target/wheels -name "*.whl")
        python -c "import pyo3_linalg_example"

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: target/wheels/*.whl
