name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  package:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install gfortran
      run: sudo apt update && sudo apt install -y gfortran
    - name: install maturin
      run: |
        pip3 install maturin
        pip3 show maturin
        echo "::add-path::$HOME/.local/bin"
    - name: Build wheel
      run: maturin build --manylinux=off
