name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install gfortran
        run: sudo apt update && sudo apt install -y gfortran

      - uses: actions/setup-python@v2
        with:
          python-versions: [3.6, 3.7, 3.8]

      - name: install maturin
        run: |
          pip3 install maturin
          pip3 show maturin
          echo "::add-path::$HOME/.local/bin"

      - name: Build wheel
        run: maturin build --manylinux=off

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/wheels/*.whl

  test:
    needs: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        minor-version: [6, 7, 8]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels

      - uses: actions/setup-python@v2
        with:
          python-versions: 3.${{ matrix.minor-version }}

      - name: Test
        run: |
          CP3=cp3${{ matrix.minor-version }}
          python -m pip install target/wheels/pyo3_linalg_example-0.1.0-${CP3}-${CP3}-linux_x86_64.whl
          python -c "import pyo3_linalg_example"
